# Generated by Django 3.0 on 2019-12-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191211_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='accountId',
            new_name='account',
        ),
    ]
