# Generated by Django 3.0 on 2019-12-16 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 11, 31, 10, 869376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 11, 31, 10, 869376, tzinfo=utc)),
        ),
    ]
